// <auto-generated />
using System;
using Lca.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lca.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LcaDbContext))]
    [Migration("20260829054041_AddAiGovernanceAndProductDrafts")]
    partial class AddAiGovernanceAndProductDrafts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lca.Core.Catalog.Category", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,0)")
                        .HasColumnName("CategoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<bool?>("DisplaySubCategory")
                        .HasColumnType("bit");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CategoryIcon");

                    b.Property<string>("Name")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("CategoryName");

                    b.Property<string>("NotificationImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ParentCategoryId")
                        .HasColumnType("numeric(18,0)")
                        .HasColumnName("ParentCategoryID");

                    b.HasKey("Id")
                        .HasName("PK_CategoryMastertbl");

                    b.ToTable("CategoryMastertbl", "dbo");
                });

            modelBuilder.Entity("Lca.Core.Catalog.Product", b =>
                {
                    b.Property<string>("ItemCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("CategoryId")
                        .HasColumnType("numeric(18,0)")
                        .HasColumnName("CategoryID");

                    b.Property<string>("CreatedSource")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("Manual");

                    b.Property<decimal?>("DealerRate")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("Delearrt");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image1")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Image2")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Image3")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Image4")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Image5")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Image6")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Image7")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Image8")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Image9")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("IsDisabled")
                        .HasColumnType("bit")
                        .HasColumnName("Disable");

                    b.Property<bool>("IsDraft")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Item");

                    b.Property<decimal?>("RetailRate")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("Rretailrt");

                    b.Property<string>("Specification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThumbnailImage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ThumbImage");

                    b.Property<decimal?>("WholesaleRate")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("Wholesaler");

                    b.HasKey("ItemCode")
                        .HasName("PK_Mobile_ItemMaster");

                    b.ToTable("Mobile_ItemMaster", "dbo");
                });

            modelBuilder.Entity("Lca.Core.Governance.AIImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("AuditLogId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SlotPosition")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Draft");

                    b.HasKey("Id")
                        .HasName("PK_AIImages");

                    b.HasIndex("ProductId", "SlotPosition", "Status");

                    b.ToTable("AIImages", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_AIImages_SlotPosition", "[SlotPosition] BETWEEN 1 AND 9");

                            t.HasCheckConstraint("CK_AIImages_Status", "[Status] IN ('Draft','Approved','Rejected')");
                        });
                });

            modelBuilder.Entity("Lca.Core.Governance.ApprovalQueueItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByAgent")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("DraftPayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK_ApprovalQueue");

                    b.HasIndex("TenantId", "Status", "CreatedAt");

                    b.ToTable("ApprovalQueue", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_ApprovalQueue_EntityType", "[EntityType] IN ('Product','Media','MarketingPost','LogisticsBooking')");

                            t.HasCheckConstraint("CK_ApprovalQueue_Status", "[Status] IN ('Pending','Approved','Rejected')");
                        });
                });

            modelBuilder.Entity("Lca.Core.Governance.AIImage", b =>
                {
                    b.HasOne("Lca.Core.Catalog.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_AIImages_Mobile_ItemMaster");

                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
