"use client";

import { FormEvent, ReactNode, useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";

type TenantStatus = "Active" | "Inactive";
type Tenant = { id:number; name:string; slug:string; status:TenantStatus; tenantUsers:number; products:number; customers:number; createdAtUtc:string; updatedAtUtc:string };
type TenantUser = { id:string; email:string; isActive:boolean; emailConfirmed:boolean; requiresPasswordSetup:boolean; tenantId:number; membershipStatus:TenantStatus };
type Audit = { id:number; actorUserId:string; action:string; targetType:string; targetId:string; tenantId:number|null; occurredAtUtc:string; details:string|null };
type Page<T> = { items:T[]; page:number; pageSize:number; totalCount:number };
type Dashboard = { totalTenants:number; activeTenants:number; inactiveTenants:number; totalTenantUsers:number; effectiveActiveTenantUsers:number; totalProducts:number; totalCustomers:number; tenantUsage:{tenantId:number;name:string;tenantUsers:number;products:number;customers:number}[]; recentTenants:Tenant[]; recentActivity:Audit[]; generatedAtUtc:string };
type Api = <T>(path:string, init?:RequestInit)=>Promise<T>;

export function PlatformLogin() {
  const router = useRouter();
  const [identity,setIdentity]=useState(""); const [password,setPassword]=useState(""); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
  async function submit(event:FormEvent){event.preventDefault();setBusy(true);setError("");try{const response=await fetch("/api/v1/platform/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({userNameOrEmail:identity,password})});if(!response.ok)throw new Error("Email or password is incorrect.");const body=await response.json() as {accessToken:string};sessionStorage.setItem("lca_platform_token",body.accessToken);router.push("/platform");}catch(reason){setError(reason instanceof Error?reason.message:"Login is unavailable.");}finally{setBusy(false)}}
  return <main className="loginShell platformTheme"><section className="loginIntro"><p className="eyebrow">LCA · Platform Owner</p><h1>Operate the SaaS platform.</h1><p>Manage businesses, account access, and platform activity without entering a Tenant&apos;s business context.</p></section><form className="loginForm" onSubmit={submit}><h2>Platform sign in</h2><label>Email or username<input autoComplete="username" required value={identity} onChange={e=>setIdentity(e.target.value)}/></label><label>Password<input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<p className="alertInline">{error}</p>}<button disabled={busy}>{busy?"Signing in…":"Sign in"}</button><Link href="/platform/forgot-password">Forgot password?</Link></form></main>;
}

function PlatformFrame({children}:{children:(api:Api)=>ReactNode}) {
  const router = useRouter();
  const [token,setToken]=useState<string|null|undefined>(undefined); const [error,setError]=useState("");
  useEffect(()=>{const stored=sessionStorage.getItem("lca_platform_token");if(!stored){router.replace("/platform/login");return;}fetch("/api/v1/platform/auth/me",{headers:{Authorization:`Bearer ${stored}`}}).then(response=>{if(!response.ok)throw new Error();setToken(stored);}).catch(()=>{sessionStorage.removeItem("lca_platform_token");router.replace("/platform/login");});},[router]);
  const logout=useCallback(()=>{sessionStorage.removeItem("lca_platform_token");router.push("/platform/login");},[router]);
  const api=useCallback(async<T,>(path:string,init:RequestInit={})=>{try{if(!token)throw new Error("Platform session is unavailable.");const headers=new Headers(init.headers);headers.set("Authorization",`Bearer ${token}`);if(init.body)headers.set("Content-Type","application/json");const response=await fetch(path,{...init,headers});if(response.status===401||response.status===403){logout();throw new Error("Your platform session has ended.");}if(!response.ok){const body=await response.json().catch(()=>null) as {detail?:string;title?:string}|null;throw new Error(body?.detail??body?.title??`Request failed (${response.status}).`);}return response.status===204?undefined as T:await response.json() as T;}catch(reason){setError(reason instanceof Error?reason.message:"The platform request failed.");throw reason;}},[token,logout]);
  if(token===undefined)return <main className="empty">Opening Platform administration…</main>;
  return <div className="appShell platformTheme"><header className="appHeader"><div><span className="brandMark">LCA</span><span className="tenantLabel">Platform Owner administration</span></div><button className="quietButton" onClick={logout}>Sign out</button></header><nav className="tabs"><Link href="/platform">Dashboard</Link><Link href="/platform/tenants">Tenants</Link><Link href="/platform/audit">Audit</Link></nav>{error&&<p className="alert">{error}<button onClick={()=>setError("")}>×</button></p>}{children(api)}</div>;
}

export function PlatformDashboardView(){const[data,setData]=useState<Dashboard|null>(null);return <PlatformFrame>{api=><DashboardContent api={api} data={data} setData={setData}/>}</PlatformFrame>}
function DashboardContent({api,data,setData}:{api:Api;data:Dashboard|null;setData:(value:Dashboard)=>void}){useEffect(()=>{void api<Dashboard>("/api/v1/platform/dashboard").then(setData).catch(()=>undefined);},[api,setData]);if(!data)return <main className="empty">Loading dashboard…</main>;const cards=[["Tenants",data.totalTenants],["Active tenants",data.activeTenants],["Tenant users",data.totalTenantUsers],["Effective users",data.effectiveActiveTenantUsers],["Products",data.totalProducts],["Customers",data.totalCustomers]];return <main className="workspace"><section className="sectionHeader"><div><p className="eyebrow">Platform dashboard</p><h1>Current platform</h1><p>Aggregates from the new shared SQL Server database.</p></div></section><div className="metricGrid">{cards.map(([label,value])=><article key={label}><small>{label}</small><strong>{value}</strong></article>)}</div><section className="platformGrid"><div><h2>Tenant usage</h2><div className="tableWrap"><table><thead><tr><th>Tenant</th><th>Users</th><th>Products</th><th>Customers</th></tr></thead><tbody>{data.tenantUsage.map(row=><tr key={row.tenantId}><td>{row.name}</td><td>{row.tenantUsers}</td><td>{row.products}</td><td>{row.customers}</td></tr>)}</tbody></table></div></div><div><h2>Recent activity</h2><AuditList entries={data.recentActivity}/></div></section></main>}

export function PlatformTenantsView(){return <PlatformFrame>{api=><TenantsContent api={api}/>}</PlatformFrame>}
function TenantsContent({api}:{api:Api}){const[data,setData]=useState<Page<Tenant>|null>(null);const[search,setSearch]=useState("");const[creating,setCreating]=useState(false);const load=useCallback(()=>api<Page<Tenant>>(`/api/v1/platform/tenants?search=${encodeURIComponent(search)}`).then(setData),[api,search]);useEffect(()=>{void load().catch(()=>undefined)},[load]);return <main className="workspace"><section className="sectionHeader"><div><p className="eyebrow">Businesses</p><h1>Tenants</h1><p>{data?.totalCount??0} registered businesses</p></div><button onClick={()=>setCreating(true)}>Create Tenant</button></section><div className="filters"><label>Search<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Name or slug"/></label></div><div className="tableWrap"><table><thead><tr><th>Name</th><th>Slug</th><th>Status</th><th>Users</th><th>Products</th><th>Customers</th></tr></thead><tbody>{data?.items.map(t=><tr key={t.id}><td><Link href={`/platform/tenants/${t.id}`}><strong>{t.name}</strong></Link></td><td>{t.slug}</td><td><span className={`statusPill ${t.status.toLowerCase()}`}>{t.status}</span></td><td>{t.tenantUsers}</td><td>{t.products}</td><td>{t.customers}</td></tr>)}</tbody></table></div>{creating&&<TenantForm api={api} close={()=>setCreating(false)} saved={async()=>{setCreating(false);await load()}}/>}</main>}
function TenantForm({api,close,saved}:{api:Api;close:()=>void;saved:()=>Promise<void>}){const[name,setName]=useState("");const[slug,setSlug]=useState("");const[error,setError]=useState("");async function submit(e:FormEvent){e.preventDefault();try{await api("/api/v1/platform/tenants",{method:"POST",body:JSON.stringify({name,slug})});await saved()}catch(reason){setError(reason instanceof Error?reason.message:"Unable to create Tenant.")}}return <div className="modalBackdrop"><section className="drawer"><header><h2>Create Tenant</h2><button className="iconButton" onClick={close}>×</button></header><form onSubmit={submit}><fieldset><div className="formGrid"><label>Name<input required maxLength={200} value={name} onChange={e=>setName(e.target.value)}/></label><label>Slug<input required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" value={slug} onChange={e=>setSlug(e.target.value.toLowerCase())}/></label></div></fieldset>{error&&<p className="alertInline">{error}</p>}<footer><button type="button" className="secondaryButton" onClick={close}>Cancel</button><button>Create</button></footer></form></section></div>}

export function PlatformTenantDetailView({tenantId}:{tenantId:number}){return <PlatformFrame>{api=><TenantDetail api={api} tenantId={tenantId}/>}</PlatformFrame>}
function TenantDetail({api,tenantId}:{api:Api;tenantId:number}){
  const[tenant,setTenant]=useState<Tenant|null>(null);const[users,setUsers]=useState<TenantUser[]>([]);const[email,setEmail]=useState("");const[name,setName]=useState("");const[slug,setSlug]=useState("");const[notice,setNotice]=useState("");
  const load=useCallback(async()=>{const values=await Promise.all([api<Tenant>(`/api/v1/platform/tenants/${tenantId}`),api<TenantUser[]>(`/api/v1/platform/tenants/${tenantId}/users`)]);setTenant(values[0]);setName(values[0].name);setSlug(values[0].slug);setUsers(values[1]);},[api,tenantId]);
  useEffect(()=>{void Promise.all([api<Tenant>(`/api/v1/platform/tenants/${tenantId}`),api<TenantUser[]>(`/api/v1/platform/tenants/${tenantId}/users`)]).then(values=>{setTenant(values[0]);setName(values[0].name);setSlug(values[0].slug);setUsers(values[1])}).catch(()=>undefined)},[api,tenantId]);
  async function provision(e:FormEvent){e.preventDefault();try{const result=await api<{setupEmail:string}>(`/api/v1/platform/tenants/${tenantId}/users`,{method:"POST",body:JSON.stringify({email})});setEmail("");setNotice(result.setupEmail==="Sent"?"User provisioned and setup email sent.":`User provisioned; setup email status: ${result.setupEmail}. You can resend it.`);await load()}catch{setNotice("")}}
  async function updateTenant(e:FormEvent){e.preventDefault();try{await api(`/api/v1/platform/tenants/${tenantId}`,{method:"PUT",body:JSON.stringify({name,slug})});setNotice("Tenant details updated.");await load()}catch{setNotice("")}}
  async function tenantStatus(){if(!tenant)return;try{await api(`/api/v1/platform/tenants/${tenantId}/status`,{method:"PUT",body:JSON.stringify({status:tenant.status==="Active"?"Inactive":"Active"})});setNotice(`Tenant ${tenant.status==="Active"?"deactivated":"activated"}. Existing sessions must sign in again.`);await load()}catch{setNotice("")}}
  return <main className="workspace">{!tenant?<p className="empty">Loading Tenant…</p>:<><section className="sectionHeader"><div><p className="eyebrow">Tenant {tenant.id}</p><h1>{tenant.name}</h1><p>{tenant.slug} · {tenant.products} Products · {tenant.customers} Customers</p></div><button className="secondaryButton" onClick={()=>void tenantStatus()}>{tenant.status==="Active"?"Deactivate":"Activate"} Tenant</button></section>{notice&&<p className="successBanner">{notice}</p>}<form className="tenantMetadataEditor" onSubmit={updateTenant}><label>Name<input required maxLength={200} value={name} onChange={e=>setName(e.target.value)}/></label><label>Slug<input required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" value={slug} onChange={e=>setSlug(e.target.value.toLowerCase())}/></label><button>Save Tenant details</button></form><section className="platformGrid"><div><h2>Tenant users</h2><div className="tableWrap"><table><thead><tr><th>Email</th><th>Setup</th><th>Account</th><th>Membership</th><th>Actions</th></tr></thead><tbody>{users.map(user=><UserRow key={user.id} api={api} user={user} reload={load} notify={setNotice}/>)}</tbody></table></div></div><form className="inlineEditor" onSubmit={provision}><h2>Provision Tenant user</h2><p className="muted">The user receives a password setup link directly by email. Platform administrators never see it.</p><label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><button>Provision and email setup</button></form></section></>}</main>
}
function UserRow({api,user,reload,notify}:{api:Api;user:TenantUser;reload:()=>Promise<void>;notify:(value:string)=>void}){async function account(){try{await api(`/api/v1/platform/users/${user.id}/status`,{method:"PUT",body:JSON.stringify({isActive:!user.isActive})});await reload()}catch{notify("")}}async function membership(){try{await api(`/api/v1/platform/tenants/${user.tenantId}/users/${user.id}/membership-status`,{method:"PUT",body:JSON.stringify({status:user.membershipStatus==="Active"?"Inactive":"Active"})});await reload()}catch{notify("")}}async function resend(){try{const result=await api<{delivery:string}>(`/api/v1/platform/users/${user.id}/initial-password-setup-email`,{method:"POST"});notify(`Setup email status: ${result.delivery}.`)}catch{notify("")}}return <tr><td>{user.email}</td><td>{user.requiresPasswordSetup?"Awaiting setup":user.emailConfirmed?"Established":"Unconfirmed"}</td><td>{user.isActive?"Active":"Inactive"}</td><td>{user.membershipStatus}</td><td className="rowActions">{user.requiresPasswordSetup&&<button className="textButton" onClick={()=>void resend()}>Resend setup email</button>}<button className="textButton" onClick={()=>void account()}>{user.isActive?"Disable account":"Enable account"}</button><button className="textButton" onClick={()=>void membership()}>{user.membershipStatus==="Active"?"Disable membership":"Enable membership"}</button></td></tr>}

export function PlatformAuditView(){return <PlatformFrame>{api=><AuditContent api={api}/>}</PlatformFrame>}
function AuditContent({api}:{api:Api}){const[data,setData]=useState<Page<Audit>|null>(null);useEffect(()=>{void api<Page<Audit>>("/api/v1/platform/audit").then(setData).catch(()=>undefined)},[api]);return <main className="workspace"><section className="sectionHeader"><div><p className="eyebrow">Governance</p><h1>Platform audit</h1><p>Non-secret administrative activity.</p></div></section><AuditList entries={data?.items??[]}/></main>}
function AuditList({entries}:{entries:Audit[]}){return <div className="auditList">{entries.map(value=><article key={value.id}><strong>{value.action}</strong><span>{value.targetType} · {value.targetId}</span><time>{new Date(value.occurredAtUtc).toLocaleString()}</time></article>)}{entries.length===0&&<p className="empty">No platform activity yet.</p>}</div>}
